# Generated by Django 2.2 on 2020-05-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': (('view_viewlog', '查看权限'),),
                'default_permissions': (),
            },
        ),
    ]
