# Generated by Django 2.2 on 2020-04-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('sex', models.IntegerField(choices=[('0', '男'), ('1', '女')], default=0, verbose_name='性别')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
    ]
