# Generated by Django 2.2 on 2020-05-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20200523_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='instance_name',
            field=models.CharField(max_length=100, verbose_name='实例的显示名称'),
        ),
    ]
