# Generated by Django 2.2 on 2020-03-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], default=0, null=True),
        ),
    ]
